- hosts: dev
  become: true
  tasks:
   - name: install python pip
     yum:
       name: python-pip
       state: present
   - name: install Docker 
     yum:
       name: docker
       state: present
   - name: install docker for python
     pip:
       name: docker
       state: present
   - name: start a container
     docker_container:
       name: myapplication
       image: dkddkd/myimage:1.1
       state: started
       published_ports:
         - 0.0.0.0:8080:9000
